/* The committed app bundle is current, and built from the SDK.
 *
 * Both halves of MCP Apps run on `@modelcontextprotocol/ext-apps`: the host in
 * frontend/src/lib/mcpAppHost.ts, and the four views in mcp_demo_server/apps,
 * where `src/index.tsx` and the components beside it are bundled by `build.sh`
 * into the single `app.js` every app document inlines.
 *
 * The bundle is committed because the server is Python and cannot run esbuild
 * at serve time, which means it can go stale against its source with nothing to
 * notice. That is what this checks.
 *
 * The handshake itself needs no test any more. It used to: when both halves
 * were hand-written they agreed with each other and disagreed with the spec for
 * weeks, sending `clientInfo` where `ui/initialize` requires `appInfo`. The SDK
 * builds that message now, and signature_app_test.js drives a real app through
 * a real handshake against it.
 *
 * Run: node custom_demo/tests/mcp_app_conformance_test.js
 */
const assert = require("node:assert");
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const ROOT = path.join(__dirname, "..", "..");
const APPS = path.join(ROOT, "mcp_demo_server", "apps");
const BUNDLE = path.join(APPS, "app.js");

/* The build, as build.sh runs it. Every flag matters to the output bytes, so
 * the staleness check below is only honest if this list matches. */
const BANNER = "/* GENERATED by apps/build.sh from src/. Do not edit. */";
const FLAGS = [
  "--bundle", "--format=iife", "--minify", "--target=es2020",
  "--jsx=automatic", "--loader:.tsx=tsx",
  '--define:process.env.NODE_ENV="production"',
];

let passed = 0;
function ok(name, fn) {
  fn();
  passed++;
  console.log("  ok -", name);
}

console.log("MCP App bundle");

ok("is committed, so the Python server can serve it without a build", () => {
  assert.ok(fs.existsSync(BUNDLE), "app.js is missing: run mcp_demo_server/apps/build.sh");
  assert.ok(fs.statSync(BUNDLE).size > 100_000, "app.js looks unbundled");
});

ok("says it is generated, so nobody edits it by hand", () => {
  assert.match(fs.readFileSync(BUNDLE, "utf8").slice(0, 200), /GENERATED by apps\/build\.sh/);
});

ok("ships React's production build, not its development one", () => {
  // The development build carries every warning and invariant message, and
  // costs both the download and a slower render. `NODE_ENV` in build.sh is what
  // defines them away, and a bundle built without it looks fine until someone
  // measures it.
  const src = fs.readFileSync(BUNDLE, "utf8");
  assert.ok(
    !src.includes("react-dom.development"),
    "app.js was built without NODE_ENV=production",
  );
});

ok("is current with its source", () => {
  // The one failure mode a committed artifact has. Rebuild into a temp file and
  // compare: a mismatch means someone changed something under src/ and did not
  // run build.sh, and the server would keep serving the old apps.
  const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "mcpapp-")), "app.js");
  execFileSync(
    "npx",
    ["--prefix", path.join(ROOT, "frontend"), "esbuild", "src/index.tsx",
     ...FLAGS, `--outfile=${out}`, `--banner:js=${BANNER}`],
    { cwd: APPS, env: { ...process.env, NODE_PATH: path.join(ROOT, "frontend", "node_modules") },
      stdio: "pipe" },
  );
  assert.strictEqual(
    fs.readFileSync(out, "utf8"),
    fs.readFileSync(BUNDLE, "utf8"),
    "app.js is stale: run mcp_demo_server/apps/build.sh and commit the result",
  );
});

console.log(`\n${passed} passed`);
