/* The committed view bundle is current, and built from the SDK.
 *
 * Both halves of MCP Apps now run on `@modelcontextprotocol/ext-apps`: the host
 * in frontend/src/lib/mcpAppHost.ts, and the view in mcp_demo_server/apps,
 * where `src/bridge.src.js` is bundled by `build.sh` into `bridge.js`.
 *
 * The bundle is committed because the server is Python and cannot run esbuild
 * at serve time, which means it can go stale against its source with nothing to
 * notice. That is what this checks.
 *
 * The handshake itself needs no test any more. It used to: when both halves
 * were hand-written they agreed with each other and disagreed with the spec for
 * weeks, sending `clientInfo` where `ui/initialize` requires `appInfo`. The SDK
 * builds that message now, and signature_app_test.js drives a real app through
 * a real handshake against it.
 *
 * Run: node custom_demo/tests/mcp_app_conformance_test.js
 */
const assert = require("node:assert");
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const ROOT = path.join(__dirname, "..", "..");
const APPS = path.join(ROOT, "mcp_demo_server", "apps");
const BUNDLE = path.join(APPS, "bridge.js");

let passed = 0;
function ok(name, fn) {
  fn();
  passed++;
  console.log("  ok -", name);
}

console.log("MCP App view bundle");

ok("is committed, so the Python server can serve it without a build", () => {
  assert.ok(fs.existsSync(BUNDLE), "bridge.js is missing: run mcp_demo_server/apps/build.sh");
  assert.ok(fs.statSync(BUNDLE).size > 100_000, "bridge.js looks unbundled");
});

ok("says it is generated, so nobody edits it by hand", () => {
  assert.match(fs.readFileSync(BUNDLE, "utf8").slice(0, 200), /GENERATED by apps\/build\.sh/);
});

ok("exposes the surface the four app files call", () => {
  const src = fs.readFileSync(path.join(APPS, "src", "bridge.src.js"), "utf8");
  // A rename here is invisible until an app calls a method that is gone.
  for (const method of ["onInit", "call", "read", "openLink", "ready"]) {
    assert.match(src, new RegExp(`\\b${method}\\s*\\(`), `McpApp.${method} is missing`);
  }
});

ok("is current with its source", () => {
  // The one failure mode a committed artifact has. Rebuild into a temp file and
  // compare: a mismatch means someone changed the source and did not run
  // build.sh, and the server would keep serving the old client.
  const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "mcpapp-")), "bridge.js");
  execFileSync(
    "npx",
    ["--prefix", path.join(ROOT, "frontend"), "esbuild", "src/bridge.src.js",
     "--bundle", "--format=iife", "--minify", "--target=es2020", `--outfile=${out}`,
     "--banner:js=/* GENERATED by apps/build.sh from src/bridge.src.js. Do not edit. */"],
    { cwd: APPS, env: { ...process.env, NODE_PATH: path.join(ROOT, "frontend", "node_modules") },
      stdio: "pipe" },
  );
  assert.strictEqual(
    fs.readFileSync(out, "utf8"),
    fs.readFileSync(BUNDLE, "utf8"),
    "bridge.js is stale: run mcp_demo_server/apps/build.sh and commit the result",
  );
});

console.log(`\n${passed} passed`);
