#!/usr/bin/env bash
# Bundle the MCP Apps view client into a single inlineable script.
#
#   ./mcp_demo_server/apps/build.sh
#
# Why a build at all: an app is served as a `ui://` resource and rendered in a
# sandboxed iframe with an opaque origin, so it can fetch nothing. Everything,
# the SDK included, has to be inside the document. That is the same reason
# Excalidraw's app is 432KB and the reference server's is 607KB.
#
# The output is committed, because the server is Python and cannot run a
# bundler at serve time. Rebuild and commit whenever src/bridge.src.js changes;
# tests/mcp_app_bundle_test.js fails if the two drift.
#
# esbuild comes from the SPA's node_modules, which is the only place this repo
# installs node packages.
set -euo pipefail
cd "$(dirname "$0")"
ROOT=../..
# NODE_PATH because esbuild resolves from the ENTRY file's directory, and
# nothing above mcp_demo_server has a node_modules.
NODE_PATH="$ROOT/frontend/node_modules" \
npx --prefix "$ROOT/frontend" esbuild src/bridge.src.js \
  --bundle --format=iife --minify --target=es2020 \
  --outfile=bridge.js \
  --banner:js="/* GENERATED by apps/build.sh from src/bridge.src.js. Do not edit. */"
printf 'built bridge.js: %s bytes\n' "$(wc -c < bridge.js | tr -d ' ')"
