#!/usr/bin/env bash
# Bundle every MCP App in this server into one inlineable script.
#
#   ./mcp_demo_server/apps/build.sh
#
# Why a build at all: an app is served as a `ui://` resource and rendered in a
# sandboxed iframe with an opaque origin, so it can fetch nothing. Everything,
# React and the Apps SDK included, has to be inside the document. That is the
# same reason Excalidraw's app is 432KB and the reference server's is 607KB.
#
# Why one bundle for four apps: React is most of the weight, and four bundles
# would commit four copies of it. src/index.tsx imports all four components and
# mounts whichever the document's `#root` names in `data-app`.
#
# The output is committed, because the server is Python and cannot run a
# bundler at serve time. Rebuild and commit whenever anything under src/
# changes; custom_demo/tests/mcp_app_conformance_test.js rebuilds into a temp
# file and fails if the committed bytes differ.
#
# esbuild comes from the SPA's node_modules, which is the only place this repo
# installs node packages.
set -euo pipefail
cd "$(dirname "$0")"
ROOT=../..
# NODE_PATH because esbuild resolves from the ENTRY file's directory, and
# nothing above mcp_demo_server has a node_modules.
#
# NODE_ENV=production is load-bearing: React ships its development build,
# warnings and all, to anything that does not define it away.
NODE_PATH="$ROOT/frontend/node_modules" \
npx --prefix "$ROOT/frontend" esbuild src/index.tsx \
  --bundle --format=iife --minify --target=es2020 \
  --jsx=automatic --loader:.tsx=tsx \
  --define:process.env.NODE_ENV='"production"' \
  --outfile=app.js \
  --banner:js="/* GENERATED by apps/build.sh from src/. Do not edit. */"
printf 'built app.js: %s bytes\n' "$(wc -c < app.js | tr -d ' ')"
